DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS planets;

CREATE TABLE planets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    planet_name TEXT NOT NULL,
    comment TEXT NOT NULL
);